####################################
# Profile Settings
####################################
spring:
  profiles:
    group:
      "local": "local,common"
      "prod": "prod,common"

---
####################################
# Local Settings
####################################
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:postgresql://db-frutti-prod-7x9.aws-ap-southeast-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/Users/neo/Library/CockroachCloud/certs/db-frutti-prod-ca.crt
    username: db4user
    password: fruttisu4user
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
  data:
    rest:
      # API의 모든 요청의 기본 경로를 지정함
      base-path: /api
      # 클라이언트가 따로 페이지 크기를 요청하지 않았을 때 적용 할 기본 페이지 크기를 설정
      default-page-size: 10
      # 최대 페이지 수를 설정
      max-page-size: 10

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDB201Dialect
        check_nullability : true
        format_sql : true
    show-sql: true

cloud:
  aws:
    credentials:
      instance-profile: true
      access-key: AKIATTDOIGFNUO53JLAM
      secret-key: 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
    region:
      auto: false
      static: ap-southeast-1 # AWS SQS의 리전정보
    stack:
      auto: false
    sqs:
      queue:
        name: fdt-nft-event-testnet.fifo	# AWS에서 생성한 Queue 이름
        url: https://sqs.ap-southeast-1.amazonaws.com/247191843163/fdt-nft-event-testnet.fifo # 생성한
---
####################################
# Production Settings
####################################
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:postgresql://db-frutti-prod-7x9.aws-ap-southeast-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/home/ubuntu/frutti-api/deploy/db-frutti-prod-ca.crt
    username: db4user
    password: fruttisu4user
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDB201Dialect
        check_nullability : true
        format_sql : true
    show-sql: true
cloud:
  aws:
    credentials:
      instance-profile: true
      access-key: AKIATTDOIGFNUO53JLAM
      secret-key: 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
    region:
      static: ap-southeast-1 # AWS SQS의 리전정보
    stack:
      auto: false
    sqs:
      queue:
        name: fdt-nft-event-testnet.fifo	# AWS에서 생성한 Queue 이름
        url: https://sqs.ap-southeast-1.amazonaws.com/247191843163/fdt-nft-event-testnet.fifo # 생성한
decorator:
  datasource:
    p6spy:
      enable-logging: true
---
####################################
# Common Settings
####################################
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: "common"
server:
  port: 10001
  output:
    ansi:
      enabled: ALWAYS
  liquibase:
    change-log: classpath:db/changelog-master.xml
    default-schema:
    drop-first: false
    contexts: crdb
    enabled: true
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    org.hibernate.SQL: info