version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/build/

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: kill_process.sh
      runas: root
  ApplicationStart:
    - location: run_java.sh
      runas: root